### ISSUE TITLE
Twitter Space audio does not download if in a linux environment

### ISSUE THREAD

**Issue by Lenoix** [HoloArchivists/tslazer#1]
When the Space is finished, nothing is downloaded. The setting is ' --path $HOME/tslazer_download --withchat --fileformat %Ud_%Un_%Ui_%St_%Si_%Dy_%Dm_%Dt' and there is no tmp folder existing during the space downloading.

**Comment by ef1500** [comment]
Try cloning the repository once more to make sure you have the latest version. A quick test with your parameters downloaded the space with no errors. 

If it still does not work, let me know, and we can get to the bottom of it.

![image](https://user-images.githubusercontent.com/45581646/187055149-da430fc9-6018-4f18-a558-58741a20845e.png)
![image](https://user-images.githubusercontent.com/45581646/187055157-95e05c97-cf62-43c8-827b-75f989aae88b.png)

**Comment by Lenoix** [comment]
I have tried reclonig the repository but it still doesn't work. The OS is centos 8 and the python version is python3.10.
I tried it like this "python3.10 tslazer.py --path ./tslazer_download --withchat --fileformat %Ud_%Un_%Ui_%St_%Si_%Dy_%Dm_%Dt --space_id $space_address".

The output is like this:
```
[ChatExporter] Chat Exporting is currently only supported for Ended Spaces with a recording. To Export Chat for a live space, copy the chat token and use WebSocketDriver.py.
Finished Getting URLs, Waiting for responses
Finished Downloading Chunks
Failed To Create Subprocess.
Successfully Downloaded Twitter Space the_space_name.m4a
[ChatExporter]: Chat Thread Started
Captured 13608 Messages [Cursor: ] 63837830220388] 
 Finished Capturing Chat! Now Parsing...
```

But when you get into the tslazer_download folder, it shows like:
```
8die365baf713d8c4661e1da2
chunkindex.txt
the_space_name.txt
```
I checked and found the_space_name.txt is the Chat file. but there is no the_space_name.m4a file at all.

**Comment by ef1500** [comment]
I noticed "Failed To Create Subprocess."

That is likely because it is unable to locate ffmpeg. The script uses ffmpeg to quickly concatenate chunks into one singular twitter space. 

Make sure that you can run ffmpeg from a terminal, then try running the script again.

**Comment by Lenoix** [comment]
But I have installed ffmpeg and I tested twspace-dl(using python3.10) which works normally with it. I don't know why it can't locate ffmpeg. Is there something wrong with python? The default python version is 3.6 and I installed 3.10 with altinstall. Thank you for your patience.

**Comment by Lenoix** [comment]
You are right. The problem is with subprocess method. I think it is that the shell parameter should be specified in linux shell environment. I edited TwitterSpace.py and then everything works well.
```
subprocess.run(command, cwd=path, shell=True)
```
Thank you.

**Comment by ef1500** [comment]
Sure thing. Thank you for bringing this up to me as well; I'll update the program to change how subprocesses are handled based on the operating system.

**Comment by fireattack** [comment]
The best way is to write the commands in format of `['ffmpeg', '-f', 'concat' ...]`  and it will run properly on any OS.
