### ISSUE TITLE
Audio chunks in downloaded m4a file are out of order

### ISSUE THREAD

**Issue by pretyflaco** [HoloArchivists/tslazer#9]
It seems like the order of the audio chunks is out of sequence when playing the downloaded m4a file in various media players, including Audacity. It results in audio jumping around inconsistently and lacking coherence.

I used the following command to download the Twitter Space audio: 
`python3 tslazer.py --space_id 1lDxLnLkLXaGm --fileformat %St_%Ud --cookies=cookies.txt`. 

The output file generated is Bitcoinizing_Honduras_with_AmityAge_Adopting_Bitcoin.m4a.

As I understand, Twitter Spaces sends the audio in separate chunks, which can sometimes arrive in a non-sequential manner. The script appears to be writing the chunks as they arrive, leading to the final file being out of order.

A potential solution could involve modifying the script to store the chunks in memory or temporary files, then write them out in the correct order once all chunks have been downloaded.

I appreciate any guidance or updates to address this issue. Thank you for your assistance in advance.

**Comment by ef1500** [comment]
The program *should* take care of that; that's why we download the space only after it has completed. The issue usually arises due to issues with the chunk downloader mismatching the chunk names.

I am going to be gone for a little while starting tomorrow, so I'll have to let this one sit for a moment. If I remember correctly, the last time I had to fix this, it wasn't too bad, so it shouldn't take too long to correct the issue.

**Comment by ef1500** [comment]
I was unable to reproduce this issue on the latest version of the tool. Can you try again with the latest version of the tool?

**Comment by pretyflaco** [comment]
Hey there,

I followed your advice and grabbed the latest version of tslazer. I ran it with the command:

`python3 tslazer.py --space_id 1BRJjZZNYkVJw --fileformat %Ud_%Dy --cookies=cookies.txt`
But the problem's still there. When I play the downloaded m4a file (Adopting_Bitcoin_2023.m4a) in different players like Audacity, the audio is still all over the place.

You mentioned earlier something about the chunk downloader might be mismatching chunk names. That could be it. Whenever you've got time to take a look, I'd appreciate it.

Thanks for your help!

**Comment by ef1500** [comment]
Can you please provide me with the ID(s) (and/or the master urls) of the twitter space you are attempting to download? That might help me identify an anomaly that's hindering the output. I see that you have specified the space ID in your issue but I'm curious if you have run into issues with any others (and just to make sure we're both on the same page).

**Comment by pretyflaco** [comment]
Sure, here's the links of the twitter spaces I've downloaded with tslazer (but got out-of-sequence audio files):

https://twitter.com/AdoptingBTC/status/1679529135515787273?s=20
Space: https://twitter.com/i/spaces/1BRJjZZNYkVJw?s=20
ID: 1BRJjZZNYkVJw

https://twitter.com/AdoptingBTC/status/1676991831563698176
Space: https://twitter.com/i/spaces/1lDxLnLkLXaGm?s=20
ID: 1lDxLnLkLXaGm

https://twitter.com/AdoptingBTC/status/1674455164034461697
Space: https://twitter.com/i/spaces/1ynJOaBDloEKR?s=20
ID: 1ynJOaBDloEKR

**Comment by fireattack** [comment]
I cannot reproduce the issue (I use `1BRJjZZNYkVJw`), but I have a feeling I might know why. 

Can you try my fork (https://github.com/fireattack/tslazer) and see if the downloaded files work? 

If so, I probably can write a PR later.  

<details><summary>Details</summary>
<p>

The main issue is that the way tslazer merges raw AAC/ADTS segments (using `ffmpeg concat`) will generate non-standard MP4s that will have cause various problems with some software. At least, the final file will always report wrong duration/length.

The proper way to concatenate these segments should be using binary merge:
```python
def concat(files, output):
    output = Path(output)
    if not output.parent.exists():
        output.parent.mkdir(parents=True)
    out = output.open('wb')
    for f in files:
        f = Path(f)
        fi = f.open('rb')
        copyfileobj(fi, out)
        fi.close()
    out.close()
```
(or  `cat` in *nix,, `copy /b` in Windows) and then remuxing the final file into mp4 container in one-go. 

</p>
</details>

**Comment by pretyflaco** [comment]
I ran your fork with this command:

`python3 tslazer.py --space_id 1BRJjZZNYkVJw`

And it downloaded all 2831 chunks successfully, then merged them using ffmpeg, output was:
`[DEBUG] command is ffmpeg -loglevel error -stats -i "230718 @AdoptingBTC Building Bitcoin Economies in Brazil-twitter-space-1BRJjZZNYkVJw_merged.aac" -c copy -metadata title="Building Bitcoin Economies in Brazil" -metadata artist="AdoptingBTC" "230718 @AdoptingBTC Building Bitcoin Economies in Brazil-twitter-space-1BRJjZZNYkVJw.m4a"
size=   98686kB time=02:21:34.72 bitrate=  95.2kbits/s speed=1.05e+04x`

The file ("230718 @AdoptingBTC Building Bitcoin Economies in Brazil-twitter-space-1BRJjZZNYkVJw.m4a") was successfully created. But the problem persists - when I play it, the audio chunks are still not in the right order (actually the file is out-of-sequence in the same very same way as before).

So, seems like we're still running in circles with this one. Any other thoughts?

**Comment by fireattack** [comment]
Can you give a timestamp? I didn't listen to its entirety TBH.

**Comment by pretyflaco** [comment]
It starts right at the beginning and is continuously out-of-sequence throughout. Checking first 30 seconds should suffice. It starts with a 6 second audio chunks, then jumps to a 3 second chunk from a different timestamp and repeats approximately every 3-4 seconds.

**Comment by fireattack** [comment]
From what I can see there is no sound at all in the first 30 seconds:

![image](https://github.com/HoloArchivists/tslazer/assets/4130991/c518df95-5b84-468b-a9db-a9a372b0a821)

Can you try to update your FFMPEG to newest (6.x)? Just place a binary in the same folder.

**Comment by pretyflaco** [comment]
Hey, just tried again with FFmpeg version 6.0 
`ffmpeg -version
ffmpeg version 6.0 Copyright (c) 2000-2023 the FFmpeg developers
built with gcc 11 (Ubuntu 11.3.0-1ubuntu1~22.04.1)
configuration: 
libavutil      58.  2.100 / 58.  2.100
libavcodec     60.  3.100 / 60.  3.100
libavformat    60.  3.100 / 60.  3.100
libavdevice    60.  1.100 / 60.  1.100
libavfilter     9.  3.100 /  9.  3.100
libswscale      7.  1.100 /  7.  1.100
libswresample   4. 10.100 /  4. 10.100
`
then ran `python3 tslazer.py --space_id 1BRJjZZNYkVJw` with your fork - output:

```
[DEBUG] get 2831 chunks.
2831/2831 chunks downloaded.      
Finished Downloading Chunks.
[DEBUG] command is ffmpeg -loglevel error -stats -i "230718 @AdoptingBTC Building Bitcoin Economies in Brazil-twitter-space-1BRJjZZNYkVJw_merged.aac" -c copy -metadata title="Building Bitcoin Economies in Brazil" -metadata artist="AdoptingBTC" "230718 @AdoptingBTC Building Bitcoin Economies in Brazil-twitter-space-1BRJjZZNYkVJw.m4a"
File '230718 @AdoptingBTC Building Bitcoin Economies in Brazil-twitter-space-1BRJjZZNYkVJw.m4a' already exists. Overwrite? [y/N] y
size=   98686kB time=02:21:34.69 bitrate=  95.2kbits/s speed=6.91e+03x    
Successfully Downloaded Twitter Space 230718 @AdoptingBTC Building Bitcoin Economies in Brazil-twitter-space-1BRJjZZNYkVJw.m4a
```

but no dice, still getting the audio chunks out of order.

**Comment by fireattack** [comment]
Ok, let's try again. I think of another possibility. 

Firstly, can you confirm that what I downloaded has no issue? [download here](https://1drv.ms/u/s!Akq11jtCTJYwhLs_EybukjzK_-i6eQ?e=zBFKjk) So we're on the same page.

If mine is good but your is not, then please update my fork to newest (https://github.com/fireattack/tslazer) and run it with --keep mode (`python3 tslazer.py --space_id 1BRJjZZNYkVJw --keep`)

Afterwards, there should be a `chunks_debug.txt` file in the folder, can you please share it? Thanks.

**Comment by pretyflaco** [comment]
Yes, the audio you shared is in the right order. 

Updated to latest and ran `python3 tslazer.py --space_id 1BRJjZZNYkVJw --keep`

Output: 
`[DEBUG] get 2831 chunks.
2831/2831 chunks downloaded.      
Finished Downloading Chunks.
[DEBUG] command is ffmpeg -loglevel error -stats -i "230718 @AdoptingBTC Building Bitcoin Economies in Brazil-twitter-space-1BRJjZZNYkVJw_merged.aac" -c copy -metadata title="Building Bitcoin Economies in Brazil" -metadata artist="AdoptingBTC" "230718 @AdoptingBTC Building Bitcoin Economies in Brazil-twitter-space-1BRJjZZNYkVJw.m4a"
size=   98686kB time=02:21:34.69 bitrate=  95.2kbits/s speed=6.99e+03x    
Keep mode. Temp files are saved at chunks_1689686152_230718 @AdoptingBTC Building Bitcoin Economies in Brazil-twitter-space-1BRJjZZNYkVJw and 230718 @AdoptingBTC Building Bitcoin Economies in Brazil-twitter-space-1BRJjZZNYkVJw_merged.aac.
Successfully Downloaded Twitter Space 230718 @AdoptingBTC Building Bitcoin Economies in Brazil-twitter-space-1BRJjZZNYkVJw.m4a`

Still out of order. 
`chunks_debug.txt` attached. 

[chunks_debug.txt](https://github.com/HoloArchivists/tslazer/files/12080940/chunks_debug.txt)

**Comment by fireattack** [comment]
Thanks! That's what I thought. 

So apparently in certain OS (Ubuntu) `Path.iterdir` or `os.scandir` doesn't guarantee returning the file list in a sensible order. 

I fixed it on my fork's end.

**Comment by pretyflaco** [comment]
Yes, running PopOS. Ran with latest update and it's now in order, yay! Amazing, thank you very much! <3
